'use strict'
const express = require('express')
const path = require('path')
const fs = require('fs')
const crypto = require('crypto')
const app = express()
const PORT = process.env.PORT || 3000
const UNAME = process.env.APP_USERNAME || 'Spot'
const UPASS = process.env.APP_PASSWORD || '1234'
const sessions = {}
app.use(express.json({ limit: '20mb' }))
app.use(express.urlencoded({ extended: true }))
function makeToken() { return crypto.randomBytes(32).toString('hex') }
function getToken(req) { const c=req.headers.cookie||''; const p=c.split(';').map(x=>x.trim()).find(x=>x.startsWith('spot_session=')); return p?p.split('=')[1]:null }
function auth(req,res,next) { if(sessions[getToken(req)])return next(); if(req.path.startsWith('/api/'))return res.status(401).json({error:'Unauthorized'}); res.redirect('/login') }
const LHTML='<!DOCTYPE html><html lang="sv"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>spot.</title><style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Segoe UI,sans-serif;background:#0f0f0f;min-height:100vh;display:flex;align-items:center;justify-content:center}.c{background:#fff;border-radius:20px;padding:40px 36px;width:min(380px,92vw);box-shadow:0 24px 60px rgba(0,0,0,.4)}.logo{font-size:28px;font-weight:800;color:#b31e59;margin-bottom:4px}.tag{font-size:13px;color:#9ca3af;margin-bottom:32px}.f{margin-bottom:16px}label{display:block;font-size:12px;font-weight:600;color:#374151;margin-bottom:6px}input{width:100%;padding:11px 14px;border:1.5px solid #e5e7eb;border-radius:10px;font-size:15px;outline:none;font-family:inherit}input:focus{border-color:#b31e59}.err{color:#b31e59;font-size:13px;margin-top:8px;display:none}.err.show{display:block}button{width:100%;margin-top:8px;padding:13px;background:#b31e59;color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:600;cursor:pointer;font-family:inherit}</style></head><body><div class="c"><div class="logo">spot.</div><div class="tag">content studio</div><form method="POST" action="/login"><div class="f"><label>Användarnamn</label><input type="text" name="username" autofocus autocomplete="username"/></div><div class="f"><label>Lösenord</label><input type="password" name="password"/></div><div class="err" id="err">Fel användarnamn eller lösenord.</div><button type="submit">Logga in</button></form></div><script>if(new URLSearchParams(location.search).get("err"))document.getElementById("err").classList.add("show")<\/script></body></html>'
app.get('/login',(_,res)=>res.send(LHTML))
app.post('/login',(req,res)=>{ const{username,password}=req.body; if(username===UNAME&&password===UPASS){const t=makeToken();sessions[t]={u:username,at:Date.now()};res.setHeader('Set-Cookie','spot_session='+t+'; Path=/; HttpOnly; SameSite=Lax; Max-Age='+(60*60*24*7));return res.redirect('/')} res.redirect('/login?err=1') })
app.post('/logout',(req,res)=>{ delete sessions[getToken(req)]; res.setHeader('Set-Cookie','spot_session=; Path=/; Max-Age=0'); res.json({ok:true}) })
const BF='/tmp/spot_brand.json'
let brand={primaryColor:'#b31e59',font:'Segoe UI',tagline:'a creative studio',logoUrl:null,socialLinks:{linkedin:'',instagram:'',facebook:'',tiktok:''}}
try{if(fs.existsSync(BF))brand=JSON.parse(fs.readFileSync(BF,'utf-8'))}catch(_){}
function saveBrand(){try{fs.writeFileSync(BF,JSON.stringify(brand))}catch(_){}}
app.get('/api/brand',auth,(_,res)=>res.json(brand))
app.post('/api/brand',auth,(req,res)=>{const{primaryColor,font,tagline,socialLinks}=req.body;if(primaryColor)brand.primaryColor=primaryColor;if(font)brand.font=font;if(tagline!==undefined)brand.tagline=tagline;if(socialLinks)brand.socialLinks=Object.assign({},brand.socialLinks,socialLinks);saveBrand();res.json({ok:true,brand})})
app.post('/api/brand/logo',auth,(req,res)=>{const{dataUrl}=req.body;if(!dataUrl)return res.status(400).json({error:'no image'});brand.logoUrl=dataUrl;saveBrand();res.json({ok:true})})
function buildInject(b){
const bc=(b&&b.primaryColor)||'#b31e59'
const sc=[{key:'natural',e:'&#x1F33F;',l:'Natural',d:'Naturliga färger'},{key:'grayscale',e:'&#x26AB;',l:'Grayscale',d:'Svartvitt'},{key:'duotone',e:'&#x1F3A8;',l:'Duotone',d:'Spot.-rött'},{key:'dark',e:'&#x1F319;',l:'Dark',d:'Mörkt tema'}].map(s=>'<div onclick="window._setIS('+JSON.stringify(s.key)+',this)" data-style="'+s.key+'" style="border:2px solid #e5e7eb;border-radius:10px;padding:14px 12px;cursor:pointer;text-align:center"><div style="font-size:22px;margin-bottom:4px">'+s.e+'</div><div style="font-size:13px;font-weight:600">'+s.l+'</div><div style="font-size:11px;color:#9ca3af">'+s.d+'</div></div>').join('')
const imgM='<div style="background:#fff;border-radius:16px;padding:24px;max-width:420px;width:92%;box-shadow:0 20px 60px rgba(0,0,0,.2)"><div style="font-size:16px;font-weight:700;color:#111;margin-bottom:4px">Välj bildstil</div><div style="font-size:13px;color:#6b7280;margin-bottom:16px">Välj innan AI genererar — sparar tokens</div><div id="isg" style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:18px">'+sc+'</div><div style="display:flex;gap:8px"><button onclick="window._skipI()" style="flex:1;padding:10px;border:1.5px solid #e5e7eb;border-radius:10px;font-size:14px;color:#6b7280;background:#fff;cursor:pointer;font-family:inherit">Hoppa över</button><button id="igb" onclick="window._confI()" disabled style="flex:1;padding:10px;background:'+bc+';color:#fff;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;border:none;font-family:inherit;opacity:.5">Generera bild</button></div></div>'
const sf=['linkedin:LinkedIn:&#x1F4BC;','instagram:Instagram:&#x1F4F7;','facebook:Facebook:&#x1F465;','tiktok:TikTok:&#x1F3B5;'].map(s=>{const[k,l,i]=s.split(':');return'<div style="margin-bottom:10px"><label style="font-size:12px;font-weight:600;color:#374151;display:block;margin-bottom:4px">'+i+' '+l+'</label><input id="sl-'+k+'" type="text" placeholder="https://'+k+'.com/..." style="width:100%;padding:9px 12px;border:1.5px solid #e5e7eb;border-radius:8px;font-size:13px;font-family:inherit;outline:none"/></div>'}).join('')
const socP='<div style="background:#fff;border-radius:16px;padding:24px;max-width:400px;width:92%;box-shadow:0 20px 60px rgba(0,0,0,.2)"><div style="font-size:16px;font-weight:700;margin-bottom:4px">Sociala medier</div><div style="font-size:13px;color:#6b7280;margin-bottom:16px">Spara profillänkar för snabb åtkomst</div>'+sf+'<div style="display:flex;gap:8px;margin-top:8px"><button onclick="document.getElementById('sp-soc').style.display='none'" style="flex:1;padding:10px;border:1.5px solid #e5e7eb;border-radius:10px;font-size:14px;color:#6b7280;background:#fff;cursor:pointer;font-family:inherit">Avbryt</button><button onclick="window._saveSoc()" style="flex:1;padding:10px;background:'+bc+';color:#fff;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;border:none;font-family:inherit">Spara</button></div></div>'
const fo=['Segoe UI','Arial','Georgia','Inter','Helvetica Neue'].map(f=>'<option value="'+f+'"'+(b&&b.font===f?' selected':'')+'>'+f+'</option>').join('')
const brP='<div style="background:#fff;border-radius:16px;padding:24px;max-width:440px;width:92%;max-height:88vh;overflow-y:auto;box-shadow:0 20px 60px rgba(0,0,0,.2)"><div style="font-size:16px;font-weight:700;margin-bottom:16px">&#9881; Varmärkesinställningar</div><div style="margin-bottom:14px"><label style="font-size:12px;font-weight:600;color:#374151;display:block;margin-bottom:6px">Logotyp</label><div id="lp" onclick="document.getElementById('li').click()" style="width:72px;height:72px;border-radius:12px;border:2px dashed #e5e7eb;display:flex;align-items:center;justify-content:center;cursor:pointer;overflow:hidden;background:#f9fafb">'+(b&&b.logoUrl?'<img src="'+b.logoUrl+'" style="width:100%;height:100%;object-fit:cover"/>'  :'<span style="font-size:11px;color:#9ca3af;text-align:center">+ Ladda upp</span>')+'</div><input id="li" type="file" accept="image/*" style="display:none" onchange="window._upLogo(this)"/></div><div style="margin-bottom:14px"><label style="font-size:12px;font-weight:600;color:#374151;display:block;margin-bottom:6px">Primärfärg</label><div style="display:flex;align-items:center;gap:8px"><input id="bpc" type="color" value="'+bc+'" style="width:38px;height:34px;border:none;border-radius:8px;cursor:pointer;padding:2px"/><input id="bph" type="text" value="'+bc+'" style="flex:1;padding:9px 12px;border:1.5px solid #e5e7eb;border-radius:8px;font-size:13px;font-family:inherit;outline:none"/></div></div><div style="margin-bottom:14px"><label style="font-size:12px;font-weight:600;color:#374151;display:block;margin-bottom:6px">Typsnitt</label><select id="bpf" style="width:100%;padding:9px 12px;border:1.5px solid #e5e7eb;border-radius:8px;font-size:13px;font-family:inherit;outline:none">'+fo+'</select></div><div style="margin-bottom:18px"><label style="font-size:12px;font-weight:600;color:#374151;display:block;margin-bottom:6px">Tagline</label><input id="bpt" type="text" value="'+((b&&b.tagline)||'').replace(/"/g,'&quot;')+'" style="width:100%;padding:9px 12px;border:1.5px solid #e5e7eb;border-radius:8px;font-size:13px;font-family:inherit;outline:none"/></div><div style="display:flex;gap:8px"><button onclick="document.getElementById('sp-brand').style.display='none'" style="flex:1;padding:10px;border:1.5px solid #e5e7eb;border-radius:10px;font-size:14px;color:#6b7280;background:#fff;cursor:pointer;font-family:inherit">Avbryt</button><button onclick="window._saveBr()" style="flex:1;padding:10px;background:'+bc+';color:#fff;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;border:none;font-family:inherit">Spara</button></div></div>'
const dd='<div style="padding:12px 16px;border-bottom:1px solid #f0f0f0"><div style="font-size:13px;font-weight:700">Spot</div><div style="font-size:11px;color:#9ca3af">Administratör</div></div><button onclick="document.getElementById('sp-brand').style.display='flex';document.getElementById('sp-dd').style.display='none'" style="width:100%;padding:10px 16px;text-align:left;font-size:13px;color:#374151;font-weight:500;cursor:pointer;border:none;background:none;font-family:inherit;border-bottom:1px solid #f0f0f0">&#9881; Varmärke</button><button onclick="document.getElementById('sp-soc').style.display='flex';document.getElementById('sp-dd').style.display='none'" style="width:100%;padding:10px 16px;text-align:left;font-size:13px;color:#374151;font-weight:500;cursor:pointer;border:none;background:none;font-family:inherit;border-bottom:1px solid #f0f0f0">&#128279; Sociala medier</button><button onclick="window._logout()" style="width:100%;padding:10px 16px;text-align:left;font-size:13px;color:#b31e59;font-weight:600;cursor:pointer;border:none;background:none;font-family:inherit">&#8594; Logga ut</button>'
return[
';(function(){',
'var _K=["reviewQueue","publishedPosts","selectedChannels","manualChannels","manualTags","imageStyle"];',
'function _sv(){try{var d={};_K.forEach(function(k){d[k]=S[k];});localStorage.setItem("sp_s",JSON.stringify(d));}catch(e){}}',
'function _ld(){try{var d=JSON.parse(localStorage.getItem("sp_s")||"{}");_K.forEach(function(k){if(d[k]!==undefined)S[k]=d[k];});if(typeof renderDashboard==="function")renderDashboard();}catch(e){}}',
'_ld();setInterval(_sv,2000);window.addEventListener("beforeunload",_sv);',
'window.addEventListener("load",function(){',
'var avs=Array.from(document.querySelectorAll("div,button")).filter(function(e){var t=e.textContent.trim();return t.length===1&&/[A-Z]/.test(t)&&e.offsetWidth>20&&e.offsetWidth<64;});var av=avs[avs.length-1];',
'if(av){var de=document.createElement("div");de.id="sp-dd";de.style.cssText="display:none;position:fixed;top:52px;right:12px;background:#fff;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,.18);z-index:9999;min-width:180px;overflow:hidden;border:1px solid #f0f0f0";de.innerHTML='+JSON.stringify(dd)+';document.body.appendChild(de);av.style.cursor="pointer";av.addEventListener("click",function(e){e.stopPropagation();var d=document.getElementById("sp-dd");d.style.display=d.style.display==="none"?"block":"none";});document.addEventListener("click",function(){var d=document.getElementById("sp-dd");if(d)d.style.display="none";});window._logout=function(){fetch("/logout",{method:"POST"}).then(function(){location.href="/login";});};',
'}',
'var im=document.createElement("div");im.id="sp-img";im.style.cssText="display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:400;align-items:center;justify-content:center";im.innerHTML='+JSON.stringify(imgM)+';document.body.appendChild(im);',
'window._imgB="";window._imgOK=false;',
'window._setIS=function(s,el){S.imageStyle=s;document.querySelectorAll("#isg [data-style]").forEach(function(d){d.style.border="2px solid #e5e7eb";d.style.background="#fff";});el.style.border="2px solid '+bc+'";el.style.background="#fff5f7";var b=document.getElementById("igb");if(b){b.disabled=false;b.style.opacity="1";}};',
'window._skipI=function(){document.getElementById("sp-img").style.display="none";};',
'window._confI=function(){document.getElementById("sp-img").style.display="none";window._imgOK=true;if(window._oGBI)window._oGBI(window._imgB,true);};',
'var _oGBI=window.generateBrandImage;window._oGBI=_oGBI;',
'window.generateBrandImage=function(brief,force){if(force===true&&window._imgOK){window._imgOK=false;if(_oGBI)return _oGBI(brief,force);return;}window._imgB=brief||"";var b=document.getElementById("igb");if(b){b.disabled=true;b.style.opacity=".5";}document.querySelectorAll("#isg [data-style]").forEach(function(d){d.style.border="2px solid #e5e7eb";d.style.background="#fff";if(d.getAttribute("data-style")===S.imageStyle){d.style.border="2px solid '+bc+'";d.style.background="#fff5f7";if(b){b.disabled=false;b.style.opacity="1";}}});document.getElementById("sp-img").style.display="flex";};',
'var spe=document.createElement("div");spe.id="sp-soc";spe.style.cssText="display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:400;align-items:center;justify-content:center";spe.innerHTML='+JSON.stringify(socP)+';document.body.appendChild(spe);',
'fetch("/api/brand").then(function(r){return r.json();}).then(function(b){if(b.socialLinks){["linkedin","instagram","facebook","tiktok"].forEach(function(k){var el=document.getElementById("sl-"+k);if(el&&b.socialLinks[k])el.value=b.socialLinks[k];});}}).catch(function(){});',
'window._saveSoc=function(){var sl={};["linkedin","instagram","facebook","tiktok"].forEach(function(k){var el=document.getElementById("sl-"+k);if(el)sl[k]=el.value;});fetch("/api/brand",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({socialLinks:sl})}).then(function(){document.getElementById("sp-soc").style.display="none";});};',
'var bpe=document.createElement("div");bpe.id="sp-brand";bpe.style.cssText="display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:400;align-items:center;justify-content:center";bpe.innerHTML='+JSON.stringify(brP)+';document.body.appendChild(bpe);',
'var _bpc=document.getElementById("bpc");var _bph=document.getElementById("bph");if(_bpc)_bpc.addEventListener("input",function(){if(_bph)_bph.value=this.value;});if(_bph)_bph.addEventListener("input",function(){if(/^#[0-9a-f]{6}$/i.test(this.value)&&_bpc)_bpc.value=this.value;});',
'window._upLogo=function(inp){var f=inp.files[0];if(!f)return;var r=new FileReader();r.onload=function(e){var u=e.target.result;fetch("/api/brand/logo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dataUrl:u})}).then(function(){var lp=document.getElementById("lp");if(lp)lp.innerHTML='<img src="'+u+'" style="width:100%;height:100%;object-fit:cover"/>';});};r.readAsDataURL(f);};',
'window._saveBr=function(){var d={};var c=document.getElementById("bpc");var h=document.getElementById("bph");var f=document.getElementById("bpf");var t=document.getElementById("bpt");if(c)d.primaryColor=c.value;if(h&&/^#[0-9a-f]{6}$/i.test(h.value))d.primaryColor=h.value;if(f)d.font=f.value;if(t)d.tagline=t.value;fetch("/api/brand",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)}).then(function(){document.getElementById("sp-brand").style.display="none";});};',
'var db=document.createElement("div");db.style.cssText="display:flex;align-items:center;gap:8px;padding:8px 0;flex-wrap:wrap";db.innerHTML="<span style=\"font-size:12px;font-weight:600;color:#374151\">Period:<\/span>"+'+"<button onclick=\"window._setP(7,this)\" data-p=7 style=\"padding:5px 12px;border-radius:20px;font-size:12px;border:1.5px solid '+bc+';background:'+bc+';color:#fff;cursor:pointer;font-family:inherit\">7 dagar<\/button>"+'+"<button onclick=\"window._setP(30,this)\" data-p=30 style=\"padding:5px 12px;border-radius:20px;font-size:12px;border:1.5px solid #e5e7eb;background:#fff;color:#374151;cursor:pointer;font-family:inherit\">30 dagar<\/button>"+'+"<button onclick=\"window._setP(90,this)\" data-p=90 style=\"padding:5px 12px;border-radius:20px;font-size:12px;border:1.5px solid #e5e7eb;background:#fff;color:#374151;cursor:pointer;font-family:inherit\">3 månader<\/button>"+'+"<span id=\"plbl\" style=\"font-size:11px;color:#9ca3af\">Senaste 7 dagarna<\/span>";',
'window._dashDays=7;window._setP=function(days,btn){window._dashDays=days;document.querySelectorAll("[data-p]").forEach(function(b){b.style.background="#fff";b.style.color="#374151";b.style.borderColor="#e5e7eb";});btn.style.background="'+bc+'";btn.style.color="#fff";btn.style.borderColor="'+bc+'";var l=document.getElementById("plbl");if(l)l.textContent="Senaste "+days+" dagarna";if(typeof renderDashboard==="function")renderDashboard();};',
'var dh=Array.from(document.querySelectorAll("h1,h2,h3")).find(function(h){return h.textContent.trim()==="Dashboard";});if(dh&&dh.parentElement)dh.parentElement.insertBefore(db,dh.nextSibling);',
'var bEl=document.getElementById("briefInput");if(bEl)bEl.style.display="none";var cg=document.getElementById("modalChGrid");if(cg&&cg.parentElement)cg.parentElement.style.display="none";',
'});',
'var _oOA=window.openAIAssist;window.openAIAssist=function(){var ti=(document.getElementById("m-title")||{}).value||"";var co=(document.getElementById("m-content")||{}).value||"";var br=[ti,co].filter(Boolean).join(". ");var bEl=document.getElementById("briefInput");if(bEl)bEl.value=br;document.querySelectorAll("#modalChGrid .ch-pill").forEach(function(p){var ch=p.getAttribute("data-ch");if(S.selectedChannels&&S.selectedChannels.includes(ch))p.classList.add("active");else p.classList.remove("active");});if(_oOA)_oOA();else{var m=document.getElementById("aiAssistModal");if(m)m.style.display="flex";}};',
'var _oSP=window.selectProposal;window.selectProposal=function(ch,idx){if(_oSP)_oSP(ch,idx);var pp=S.proposals&&S.proposals[ch];if(!pp||!pp[idx])return;var p=pp[idx];var cEl=document.getElementById("m-content");var tEl=document.getElementById("m-title");if(cEl){cEl.value=p.content||"";cEl.dispatchEvent(new Event("input"));}if(tEl&&p.title){tEl.value=p.title;tEl.dispatchEvent(new Event("input"));}};',
'}());'
].join('')
}
app.get('/',auth,(req,res)=>{
try{const html=fs.readFileSync(path.join(__dirname,'poc.html'),'utf-8');const inject=buildInject(brand);const idx=html.lastIndexOf('</script>');const patched=html.slice(0,idx)+inject+html.slice(idx);res.setHeader('Content-Type','text/html; charset=utf-8');res.send(patched)}
catch(e){console.error(e);res.status(500).send('Error: '+e.message)}
})
app.post('/api/generate',auth,async(req,res)=>{
try{const{channels=['instagram'],brief=''}=req.body;const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(500).json({error:'GEMINI_API_KEY saknas'});const chList=Array.isArray(channels)?channels:[channels];const prompt='Du ar copywriter for spot. creative studio Halmstad. Ton: professionell, varm, kreativ. Brief: '+(brief||'Generellt om spot.')+'. Kanaler: '+chList.join(', ')+'. Generera EXAKT 3 korta forslag max 100 ord. Svara ENDAST med JSON-array: [{"title":"...","content":"...","hashtags":["..."],"cta":"..."},{"title":"...","content":"...","hashtags":["..."],"cta":"..."},{"title":"...","content":"...","hashtags":["..."],"cta":"..."}]';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key='+apiKey,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.9,maxOutputTokens:8192}})});const data=await r.json();if(data.error)throw new Error('Gemini: '+data.error.message);let s=(data.candidates?.[0]?.content?.parts?.[0]?.text||'').replace(/```json/g,'').replace(/```/g,'').trim();s=s.replace(/,(s*[}]])/g,'$1');const start=s.indexOf('['),end=s.lastIndexOf(']');if(start<0||end<0)throw new Error('Ingen array i svar');const flat=JSON.parse(s.slice(start,end+1));const proposals={};chList.forEach(ch=>{proposals[ch]=flat});res.json({proposals})}
catch(e){res.status(500).json({error:e.message})}
})
app.post('/api/generate-image',auth,async(req,res)=>{
try{const{brief='',style='modern'}=req.body;const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)return res.status(500).json({error:'GEMINI_API_KEY saknas'});const prompt='Professional social media image for spot. creative studio Halmstad. Style: '+style+'. Brief: '+(brief||'creative studio branding')+'. Minimalist. Brand color: '+(brand.primaryColor||'#b31e59')+'.';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key='+apiKey,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['IMAGE','TEXT']}})});const data=await r.json();if(data.error)throw new Error('Gemini: '+data.error.message);const imgPart=(data.candidates?.[0]?.content?.parts||[]).find(p=>p.inlineData?.mimeType?.startsWith('image/'));if(imgPart)return res.json({imageUrl:'data:'+imgPart.inlineData.mimeType+';base64,'+imgPart.inlineData.data});res.json({imageUrl:'https://placehold.co/1080x1080/c8003c/ffffff?text=spot.'})}
catch(e){res.status(500).json({error:e.message})}
})
app.post('/api/save-post',auth,async(req,res)=>{
try{const{Pool}=require('pg');const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});await pool.query('CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, data JSONB, created_at TIMESTAMPTZ DEFAULT NOW())');const post=req.body;await pool.query('INSERT INTO posts (id,data) VALUES ($1,$2) ON CONFLICT (id) DO UPDATE SET data=$2,created_at=NOW()',[post.id||Date.now().toString(),JSON.stringify(post)]);res.json({saved:true})}
catch(e){res.status(500).json({error:e.message})}
})
app.get('/api/published-posts',auth,async(req,res)=>{
try{const{Pool}=require('pg');const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});await pool.query('CREATE TABLE IF NOT EXISTS posts (id TEXT PRIMARY KEY, data JSONB, created_at TIMESTAMPTZ DEFAULT NOW())');const result=await pool.query("SELECT data FROM posts WHERE data->>'status' IN ('published','archived') ORDER BY created_at DESC LIMIT 200");res.json({posts:result.rows.map(r=>r.data)})}
catch(e){res.status(500).json({error:e.message})}
})
app.listen(PORT,()=>console.log('spot. running on '+PORT))
